
# Basic
title: Links
description: Links by Leah Cunningham
author:
  name: Leah Cunningham

social:
  github:           cunningleah
  linkedin:         leahcunningham
  email:            leah@cunningleah.com
  microblog:        leah.microblog.com

url: http://www.cunningleah.com/links
baseurl: ""

timezone: America/Chicago
permalink: /:year/:month/:title/

# Pagination
paginate: 50
paginate_path: /page:num/

# Feed config
feed_posts:         50

# SEO
Logo: /assets/logo/links-logo-grey-trans.png
lang: en_US

markdown: kramdown
kramdown:
  input: GFM

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  - scope:
      path:         ""
    values:
      image:        /assets/logo/links-logo-grey-trans.png

exclude: ['README.md', 'tools']

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

