name: links.thingelstad.com
url: http://example.org
description: A stylish blog using the Solarized color palette

timezone: America/Chicago
permalink: /:year/:title/

paginate: 10
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
