
# Basic
title: Link Thing
description: Links of interest for Jamie Thingelstad
author: Jamie Thingelstad

url: http://links.thingelstad.com
baseurl: ""

timezone: America/Chicago
permalink: /:year/:title/

# Pagination
paginate: 25
paginate_path: /page:num/

# Feed config
feed_posts:         50

# Analytics
google_analytics:   UA-49944629-15

markdown: kramdown
kramdown:
  input: GFM

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

exclude: ['README.md', 'tools']

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

