
# Basic
title: Link Thing
description: Links by Jamie Thingelstad
author:
  name: Jamie Thingelstad
  twitter: thingles

social:
  twitter:          thingles
  github:           thingles
  linkedin:         jthingelstad
  email:            jamie@thingelstad.com
  microblog:        jthingelstad
  pinboard:         thingles

url: https://links.thingelstad.com
baseurl: ""

timezone: America/Chicago
permalink: /:year/:month/:title/

# Pagination
paginate: 50
paginate_path: /page:num/

# Feed config
feed_posts:         50

# Analytics
google_analytics:   UA-49944629-15

# SEO
twitter:
  username: thingles
logo: /assets/logo/links-logo-grey-trans.png
lang: en_US

markdown: kramdown
kramdown:
  input: GFM

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  - scope:
      path:         ""
    values:
      image:        /assets/logo/links-logo-grey-dark.png


exclude: ['README.md', 'tools']

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

