name: links.thingelstad.com
url: http://example.org
description: Links of interest for Jamie Thingelstad

timezone: America/Chicago
permalink: /:year/:title/

url:                "http://links.thingelstad.com" # the base hostname & protocol for your site

# Pagination
paginate: 25
paginate_path: /page:num/

# Feed config
feed_posts:         50

# Analytics
google_analytics:   UA-49944629-15

markdown: kramdown
kramdown:
  input: GFM

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from